(function (root) {
  "use strict";
  const seed = {
    users: [
      ["youssef", "yo…", "youssef", "youss…", "User"],
      ["test", "test", "test", "test@…", "User"],
      ["sghrab", "GH…", "SOUF…", "sghra…", ""],
      ["sbellhas…", "BE…", "SOUF…", "sbellh…", ""],
      ["root", "CST", "CST", "root@…", ""],
      ["fnjeh", "NJ…", "FATMA", "njeh…", ""],
      ["egalve", "GA…", "EMILIO", "egalv…", ""],
      ["cst", "cst", "cst", "cst@…", ""],
      ["aanabi", "AN…", "ABDE…", "aann…", ""],
    ].map((r, i) => ({
      id: "u" + i,
      username: r[0],
      name: r[1],
      firstName: r[2],
      email: r[3],
      role: r[4],
      company: "NOVOGEL",
      active: true,
    })),
    companies: [
      {
        id: "c1",
        name: "NOVOGEL",
        email: "aannabi.novogel@gmail.com",
        phone: "51900600",
        fax: "74497285",
        customerType: "contractuelle",
        activity: "Selles|Buying",
        establishments: [],
      },
    ],
    rooms: [
      ["STOCK/TUNEL", 3],
      ["Azot_4", 1],
      ["Stock", 1],
      ["cst", 1],
      ["Ozone", 2],
      ["Chambre 0", 3],
      ["CH0/TUNEL3", 3],
      ["oxygène", 1],
    ].map((r, i) => ({
      id: "r" + i,
      name: r[0],
      contacts: ["Youssef1"],
      sensors: Array.from({ length: r[1] }, (_, j) => "Probe " + (j + 1)),
    })),
    devices: [
      ["776504", "Azot_3"],
      ["8355245", "Azot_4"],
      ["D1", "CH0/TUNEL3"],
      ["777340", "Chambre 0"],
      ["9182936", "Cst"],
      ["1508136", "oxygène"],
      ["10821984", "Ozone"],
      ["8355361", "Salle_sv/tr"],
      ["776712", "Stock"],
      ["1516996", "STOCK/TUNEL"],
    ].map((r, i) => ({
      id: "d" + i,
      code: r[0],
      name: r[1],
      location: { x: 63, y: 42 },
      sensors: [
        {
          name: r[1],
          type: "Gas concentration",
          unit: "mg/m3",
          minGauge: -100,
          maxGauge: -40,
          label: r[1],
          step: 10,
          minThreshold: 0,
          maxThreshold: 0,
        },
      ],
    })),
    contacts: [
      "Youssef12 Lamouchi",
      "youssef lamouchi",
      "Cyrine AAMRI",
      "nbayl nbayl",
      "Salem Dahmani",
    ],
    availableSensors: ["Azot_3"],
    alerts: [
      "Azot_4",
      "Salle_sv/tr S1",
      "Azot_3",
      "Stock",
      "Chambre 0 S1",
      "TUNEL3",
      "TUNEL01",
      "Chambre 0 S2",
      "Ozone",
      "oxygène",
      "STOCK/TUNEL",
      "Cst",
      "Salle_sv/tr S2",
      "Stock S2",
    ].map((name, i) => ({
      id: "a" + i,
      name,
      site: i === 5 || i === 6 ? "NOVOGEL" : "Novogel_Sfax",
      type: i === 0 ? "range" : "service",
      value: i === 0 ? 31.06 : null,
    })),
  };
  const scenes = [
    {
      id: "login",
      group: "Authentication",
      label: "01 · Sign in",
      route: "login",
      title: "Start with a sign-in.",
      description:
        "Enter an email and password. The form validates them and shows a loading state.",
      hint: "Use a sample email and any password with at least four characters. Nothing is transmitted.",
      source: "chap3/1.png · left phone",
    },
    {
      id: "login-filled",
      group: "Authentication",
      label: "02 · Filled credentials",
      route: "login",
      title: "A working login form.",
      description:
        "The second login state from the report, with editable sample credentials.",
      hint: "Click the eye to show the demo password, then Sign In.",
      source: "chap3/1.png · right phone",
    },
    {
      id: "users",
      group: "Users",
      label: "03 · User list",
      route: "users",
      title: "Manage access.",
      description:
        "The user table is recreated with expandable rows and pagination.",
      hint: "Expand a row to edit it, or use the plus beside User to add a record.",
      source: "chap3/3.png · left phone",
    },
    {
      id: "user-form",
      group: "Users",
      label: "04 · Add / edit user",
      route: "users",
      title: "Edit the actual fields.",
      description: "Name, role, company and account state belong to one form.",
      hint: "Change a field and Save. The table will reflect the saved values.",
      source: "chap3/3.png · middle phone",
    },
    {
      id: "user-saved",
      group: "Users",
      label: "05 · Saved user",
      route: "users",
      title: "See the saved result.",
      description:
        "The tenth row and the success message are driven by the local data store.",
      hint: "Open imem to edit it again. Reset demo restores the original records.",
      source: "chap3/3.png · right phone",
    },
    {
      id: "companies",
      group: "Companies",
      label: "06 · Company list",
      route: "companies",
      title: "Organize companies.",
      description:
        "Search the company list, edit contact details, or create a company.",
      hint: "Try searching for NOVOGEL. Add opens the company form.",
      source: "chap4/phone pfe5.png · left phone",
    },
    {
      id: "company-errors",
      group: "Companies",
      label: "07 · Required fields",
      route: "company-form",
      title: "Validation with context.",
      description:
        "Missing required fields are highlighted, matching the report’s error state.",
      hint: "Enter a company name, select customer type and activity, then complete the contact fields.",
      source: "chap4/phone pfe5.png · middle phone",
    },
    {
      id: "company-filled",
      group: "Companies",
      label: "08 · Completed company",
      route: "company-form",
      title: "Ready to create.",
      description:
        "The filled form remains fully editable. Establishments can be added before saving.",
      hint: "Add an establishment or Save ASTRO MAX into the company list.",
      source: "chap4/phone pfe5.png · right phone",
    },
    {
      id: "rooms",
      group: "Rooms",
      label: "09 · Room list",
      route: "rooms",
      title: "Connect rooms and probes.",
      description:
        "Each room shows its alert contact and the number of assigned sensors.",
      hint: "Add a room or open a row’s Details to edit its assignments.",
      source: "chap4/phone pfe4.png · left phone",
    },
    {
      id: "room-sensors",
      group: "Rooms",
      label: "10 · Sensor selection",
      route: "rooms",
      title: "Assign a sensor.",
      description:
        "An open, selectable sensor menu recreates the second room screenshot.",
      hint: "Check Azot_3. Choose a room name and save the assignment.",
      source: "chap4/phone pfe4.png · middle phone",
    },
    {
      id: "room-contacts",
      group: "Rooms",
      label: "11 · Alert contacts",
      route: "rooms",
      title: "Choose who receives alerts.",
      description:
        "The contact dropdown supports multiple selections within the room form.",
      hint: "Select contacts and sensors. Changes are local; no notifications are sent.",
      source: "chap4/phone pfe4.png · right phone",
    },
    {
      id: "devices",
      group: "Devices & sensors",
      label: "12 · Device list",
      route: "devices",
      title: "Manage the equipment.",
      description:
        "The device list preserves the identifiers and names visible in the report.",
      hint: "Search, inspect a device, or Add a new device with one or more sensors.",
      source: "chap4/phone pfe7.png · left phone",
    },
    {
      id: "device-form",
      group: "Devices & sensors",
      label: "13 · Device configuration",
      route: "devices",
      title: "Configure a device.",
      description:
        "Identity, location and nested sensors form a single editable record.",
      hint: "Complete the required fields and use Choose Location to place the device.",
      source: "chap4/phone pfe7.png · middle phone",
    },
    {
      id: "sensor-form",
      group: "Devices & sensors",
      label: "14 · Sensor configuration",
      route: "devices",
      title: "Give measurements meaning.",
      description:
        "Configure units, gauge bounds, label, step and alert thresholds for each sensor.",
      hint: "Scroll the form, change the gauge bounds, or add another sensor.",
      source: "chap4/phone pfe7.png · right phone",
    },
    {
      id: "overview",
      group: "Monitoring",
      label: "15 · Dashboard & map",
      route: "overview",
      title: "See the whole site.",
      description:
        "Filter devices by status, zoom and drag the map, and inspect the site marker.",
      hint: "Click the marker to inspect Azot_4 or open Live Alerts below the map.",
      source: "chap5/phone pfe9.png · left phone",
    },
    {
      id: "alerts",
      group: "Monitoring",
      label: "16 · Active alerts",
      route: "alerts",
      title: "Find the critical reading.",
      description:
        "The list separates out-of-range readings from out-of-service sensors.",
      hint: "Filter the alerts, use Locate to center the map, or open Azot_4.",
      source: "chap5/phone pfe9.png · middle phone",
    },
    {
      id: "live",
      group: "Monitoring",
      label: "17 · Live gauge",
      route: "live",
      title: "Watch the measurement.",
      description:
        "The SVG needle and numeric readout respond to local simulated readings.",
      hint: "Use the settings button to simulate new readings or change the gauge range.",
      source: "chap5/phone pfe9.png · right phone",
    },
  ];
  const exports = { seed, scenes };
  if (typeof module !== "undefined") module.exports = exports;
  else (root.CST ||= {}).data = exports;
})(typeof window !== "undefined" ? window : globalThis);
